config/routes.rb
Rails.application.routes.draw do
 

resources :users,  except:[:edit, :delete] do 
 resources :friends, except:[:edit, :delete]
end

 root  'users#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :friends
	validates :name, :phone, :company, :position, presence: true
	validates :email, uniqueness: true #somente o email do usuário~precisa ser único.
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
	validates :phone, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_user

  def create
		@friend = @user.friends.create(friend_params)
		if @friend.save
      # Quando cria a indicação ao amigo com essa linha, ele redireciona para /friends e não deveria
      # no controler está enviando para o @user caso tenha sucesso.
      # CourtesyMail.friend_email(@user, @friend).deliver
			redirect_to @user
    else
		render 'new'
		end	
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def friend_params
  	params.require(:friend).permit(:name, :email, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	before_action :load_user, only:[:show]
  
  def index
  	@users = User.all
  	@total_users = User.all.count
  end

  def show
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.create(user_params)
  		if @user.save
        CourtesyMail.user_email(@user).deliver
  			redirect_to @user
  		else
  		render 'new'
  		end	
  	
  end

  private

  def load_user
  	@user = User.find(params[:id])
  end

  def user_params
  	params.require(:user).permit(:name, :email, :phone, :company, :position)
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courtesy_mail/friend_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Olá! Seu amigo <%= @user.name %>, lhe indicou para concorrer em um de nossos eventos!</h1>
    <p>
    	Acesse e <a hreh="http://www.imasters.com.br/">cadastre-se</a> para concorrer aos principais eventos do iMasters !
    </p>
  </body>
</html>

app/views/courtesy_mail/friend_email.text.erb
Olá! <%= @friend.name %>, seu amigo <%= @user.name %> lhe indicou para concorrer na participação de um de nossos eventos!

app/views/courtesy_mail/user_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Olá! <%= @user.name %></h1>
    <p>
      teste de email usando smtp.
    </p>
  </body>
</html>

app/views/courtesy_mail/user_email.text.erb
Obrigado pela inscrição! <%= @user.name %>

app/views/friends/_form.html.erb
<br>
<div class="panel panel-primary">
	<div class="panel-heading text-uppercase">
	<p>Olá <%= @user.name.split.first %>! Obrigado por se cadastrar, indique amigos para concorrer também!</p>
	</div>	
	
	<div class="panel-body">
	<%= form_for ([@user, @user.friends.build]) do |f| %>
	<%= f.text_field :name, label: "Nome", placeholder: 'Nome', class: 'col-md-12' %>
	<%= f.text_field :email, label: "E-mail", placeholder: 'E-mail',  class: 'col-md-12' %>
	</div>

	<div class="panel-footer">
		<div class="actions">
		<%= f.button "Indicar amigo" %>
		</div>
	</div>

	<% end %>
</div>

app/views/friends/index.html.erb
<div class="container">
	<div class="list-group">
	  <ul class="list-unstyled list-inline text-uppercase">
	    <li><%= link_to "Cadastre-se", new_user_path, class: 'btn btn-info'  %> </li>
	    <li>Olá <%= @user.name.split.first %>! <%= link_to "Indique amigos para concorrer", new_user_friend_path(@user),  class: 'text text-info'  %> </li>
	  </ul>
	</div>

<p id="notice"><%= notice %></p>

	<div class="col-md-12">
	  <div class="list-group-item list-group-item-info"> <strong> Nome: </strong><%= @user.name %></div>
	  <div class="col-md-12 list-group-item list-group-item"> <strong> Email: </strong> <%= @user.email  %> </div>
	  <div class="col-md-6 list-group-item list-group-item"> <strong>  Indicações: </strong> <%= @user.friends.count  %> </div>
	  <div class="col-md-6 list-group-item list-group-item"> <strong>  Empresa: </strong> <%= @user.company  %> </div>
	</div>

	<div class="col-md-12">
		<% if @user.friends.blank? %>
			<h2> Não tem indicações</h2>
		<% else %>
			<p class="text text-default">Amigos indicados:</p>
			<% @user.friends.order("created_at DESC").each do |friend| %>
			<div class="row list-group">
			<div class="col-md-12 list-group-item">Nome: <%= friend.name %> </div>
			<div class="col-md-12 list-group-item">Email: <%= friend.email %> </div>
			</div>
			<% end %>
	<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Courtesy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<h1 class="text text-primary">Cadastre-se <small>e concorra aos principais eventos do grupo iMasters!</small></h1>
	<div class="row">
	<div class="col-md-5"><a href="http://intercon.imasters.com.br/" target="_blank"><%= image_tag 'internet_con.png', height: '60px' %></a></div>
	<div class="col-md-3"><a href="http://devcommerce2016.imasters.com.br/" target="_blank"><%= image_tag 'dev_commerce.png', width: '140PX' %></a></div>
	<div class="col-md-3"><a href="http://phpexperience2016.imasters.com.br/" target="_blank"><%= image_tag 'php_experience.png', height: '60px' %></a></div>
	</div>
</div>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<div class="container">
<div class="row">
              <div class="col-sm-10 col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 col-sm-offser-1">
                  <h1 class="page-header"></h1>
                  <div class="panel panel-primary">
                      <div class="panel-heading">Cadastro usuário</div>
                      <div class="panel-body">
						<%= simple_form_for @user do |f| %>
						<%= f.input :name %>
						<%= f.input :email %>
						<%= f.input :phone %>
						<%= f.input :company %>
						<%= f.input :position %>

						</div>	

						<div class="panel-footer">
							

						<%= f.button :submit %>

						</div>
						<% end %>
                      </div>
                  </div>
              </div>
          </div>

app/views/users/index.html.erb
<!-- Striped Table -->
<!--===================================================-->


<div class="container">
	<div class="row">
		<div class="col-sm-8 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2 col-sm-offser-2">
		<p class="text text-info"><%= @total_users %> usuários cadastrados, aproveite e <%= link_to 'Cadastre-se', new_user_path %>  para concorrer também!! </p>
	</div>
	<div class="row">
		<div class="col-sm-8 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2 col-sm-offser-2">
		<%= link_to 'Cadastre-se', new_user_path, class: "btn btn-primary" %>
		</div>
	</div>	
</div>
          <div class="row">
              <div class="col-sm-10 col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 col-sm-offser-1">
                  <h1 class="page-header"></h1>
                  <div class="panel panel-primary">
                      <div class="panel-heading">Últimos cadastros</div>
                      <div class="panel-body">
                          <table class="table table-bordered table-condensed" id="dataTable">
                              <thead>
                                  <tr>
                                      <th>Nome</th>
                                      <th>Email</th>
                                      <th>Indicações</th>
                                      <th>Empresa</th>
                                      <th>Detalhes</th>
                                      <!-- <th style="width: 10%">Excluir</th> -->
                                  </tr>
                              </thead>
                              <tbody>
                                   <% @users.order("created_at desc").each do |user| %>
                                  <tr>
                                      <td><%= link_to user.name, user_path(user) %></td>
                                      <td><%= user.email%></td>
                                      <td><%= user.friends.count %></td>
                                      <td><%= user.company %></td>
                                      <td>
                                         <%= link_to '', user_path(user), class: 'fa fa-info-circle pull-right' %>
                                      </td>
                                       <td>
                                      </td>
                                  </tr>
                                  <% end %>
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
          </div>
      </div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

	<div class="col-md-12">
	  <div class="list-group-item list-group-item-info"> <strong> Nome: </strong><%= @user.name %></div>
	  <div class="col-md-12 list-group-item list-group-item"> <strong> Email: </strong> <%= @user.email  %> </div>
	  <div class="col-md-6 list-group-item list-group-item"> <strong>  Indicações: </strong> <%= @user.friends.count  %> </div>
	  <div class="col-md-6 list-group-item list-group-item"> <strong>  Empresa: </strong> <%= @user.company  %> </div>

	</div>
	
	<div class="col-md-12">
		<% if @user.friends.blank? %>
			<h2> Não tem indicações</h2>
			<div class="form">
				<%= render 'friends/form' %>
			</div>
		<% else %>
			<div class="friends_wrapper">
				<div class="form">
				<%= render 'friends/form' %>
				</div>
			</div>

			<div class="col-md-12">
				<p class="text text-info"><strong>Amigos indicados:</strong></p>
				<% @user.friends.order("created_at DESC").each do |friend| %>
					<div class="list-group">
					<div class="list-group-item list-group-item-info">Nome: <%= friend.name %> </div>
					<div class="list-group-item list-group-item-info">Email: <%= friend.email %> </div>
					</div>
				<% end %>
			</div>
	<% end %>
	</div>
</div>